name: Broken link or incorrect item
description: Report a broken link or incorrect description
labels: [bug]
body:
  - type: input
    id: link
    attributes:
      label: Link
      description: Paste the exact URL
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What's wrong and suggested fix?
    validations:
      required: true
