name: link-check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run Lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config lychee.toml
            --max-concurrency 4
            --timeout 20
            --retry-wait-time 2
            --max-retries 2
            --no-progress
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save report
        if: always()
        run: |
          mkdir -p ./lychee
          cp -f ./lychee/out.md ./lychee/report.md || true
