name: markdown-lint
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        run: |
          npm install -g markdownlint-cli2
          markdownlint-cli2 '**/*.md' '!node_modules'
